esphome:
  name: plant-sensor
  friendly_name: Plant-Sensor

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant-Sensor Fallback Hotspot"
    password: "redacted"

captive_portal:

i2c:
  sda: GPIO8
  scl: GPIO9

globals:
  - id: page
    type: int
    initial_value: "1"

font:
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16

display:
  - platform: ssd1306_i2c
    model: SSD1306_128X32
    lambda: |-
      switch (id(page)){
            case 1:
              it.print(0, 0, id(roboto_16), "Spider Plant");
              it.printf(0, 16, id(roboto_16), "%.1f%%", id(sensor1).state);
              break;
            case 2:
              it.print(0, 0, id(roboto_16), "Ikea Plant");
              it.printf(0, 16, id(roboto_16), "%.1f%%", id(sensor2).state);
              break;
            case 3:
              it.print(0, 0, id(roboto_16), "Rubber Plant");
              it.printf(0, 16, id(roboto_16), "%.1f%%", id(sensor3).state);
              break;
            case 4:
              it.print(0, 0, id(roboto_16), "Succlent");
              it.printf(0, 16, id(roboto_16), "%.1f%%", id(sensor4).state);
              break;
          }

interval:
- interval: 5s
  then:
    - lambda: |-
        id(page) = (id(page) + 1);
        if (id(page) > 4) {
          id(page) = 1;
        }

sensor:
  - platform: adc
    pin: GPIO0
    id: sensor1
    attenuation: 12db
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          datapoints:
            - 2.3 -> 0.0
            - 0.9 -> 100.0
  - platform: adc
    pin: GPIO1
    id: sensor2
    attenuation: 12db
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          datapoints:
            - 2.3 -> 0.0
            - 0.9 -> 100.0
  - platform: adc
    pin: GPIO2
    id: sensor3
    attenuation: 12db
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          datapoints:
            - 2.3 -> 0.0
            - 0.9 -> 100.0
  - platform: adc
    pin: GPIO3
    id: sensor4
    attenuation: 12db
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          datapoints:
            - 2.3 -> 0.0
            - 0.9 -> 100.0